### ISSUE TITLE
Task Scheduler Extract Error

### ISSUE THREAD

**Issue by Lucidic15** [frankstar10/RPCS3_Updater#2]
Error when using with task scheduler when extracting.

I am running with highest privileges. 

![image](https://github.com/FrankAlbella/RPCS3_Updater/assets/90225144/2f8f4b06-239d-4705-812c-ce3553057335)

**Comment by FrankAlbella** [comment]
Hi, have you tried using the built in updater RPCS3 has now? Open RPCS3, click on `Help` at the top, then click `Check for Updates`. Let me know if that works, thanks!

**Comment by FrankAlbella** [comment]
Oh I see the problem, task scheduler is running the program from the `system32` folder. I'm not familiar with task scheduler, is it possible you can change the `start in directory` or `working directory` somewhere? Make it point to the folder RPCS3 is in, in your case it would be `G:\EmulationStation\Emulators\rpcs3\`.

**Comment by Lucidic15** [comment]
Hmmm, not that I see.

But I didnt know I can update RPCS3 inside the app now so I guess its not a
big deal. Thanks

**Comment by Lucidic15** [comment]
Hey that did work! Thanks! 
![image](https://github.com/FrankAlbella/RPCS3_Updater/assets/90225144/03609d64-14d7-42b2-9068-d66bf159d730)

**Comment by Lucidic15** [comment]
Lastly, any chance you could add a launch parameter or something that makes
it not open RPCS3 after updating?

Please and thank you.

**Comment by FrankAlbella** [comment]
Open a new issue for it and I'll add it when I get the chance
